"use client";

import type { ThemeConfig } from "antd";
import { ConfigProvider, theme as antdTheme } from "antd";
import zhCN from "antd/locale/zh_CN";
import dayjs from "dayjs";
import "dayjs/locale/zh-cn";
import { createContext, useContext, useEffect, useMemo, useState } from "react";

dayjs.locale("zh-cn");

type ThemeMode = "dark" | "light";

type ThemeContextValue = {
  mode: ThemeMode;
  toggleTheme: () => void;
};

const ThemeModeContext = createContext<ThemeContextValue | null>(null);

function readBrowserThemeMode(): ThemeMode {
  const attr = document.documentElement.getAttribute("data-theme");
  if (attr === "dark" || attr === "light") {
    return attr;
  }
  const saved = window.localStorage.getItem("kubenova-theme-mode");
  if (saved === "dark" || saved === "light") {
    return saved;
  }
  return "light";
}

export function useThemeMode() {
  const ctx = useContext(ThemeModeContext);
  if (!ctx) {
    throw new Error("主题上下文不可用");
  }
  return ctx;
}

const fontFamily = '"Geist", "IBM Plex Sans", "PingFang SC", "Microsoft YaHei", sans-serif';

const knDark = {
  bg: "#090d14",
  layout: "#090d14",
  shell: "#0d131d",
  surface: "#111720",
  surfaceRaised: "#171e29",
  surfaceElevated: "#1a2230",
  surfaceSoft: "rgba(148, 163, 184, 0.11)",
  border: "rgba(148, 163, 184, 0.18)",
  borderSubtle: "rgba(148, 163, 184, 0.12)",
  text: "#edf1f7",
  textSecondary: "#a3adbc",
  textTertiary: "#6f7a8c",
  textDisabled: "#566274",
  primary: "#4f8cff",
  primaryHover: "#6da0ff",
  primaryActive: "#3f7ded",
  primarySoft: "rgba(79, 140, 255, 0.16)",
  primarySofter: "rgba(79, 140, 255, 0.08)",
  accent: "#22d3ee",
  accentHover: "#67d8f5",
  accentActive: "#0891b2",
  accentSoft: "rgba(34, 211, 238, 0.14)",
  accentSofter: "rgba(34, 211, 238, 0.08)",
  info: "#67d8f5",
  success: "#3ddc97",
  warning: "#f2b84b",
  danger: "#ff6b6b",
  dangerActive: "#ef4444",
  control: "#111720",
  controlHover: "#171e29",
  controlActive: "#1a2230",
  overlay: "#1a2230",
  overlayStrong: "#171e29",
  mask: "rgba(2, 6, 10, 0.62)",
  shadow: "0 18px 38px rgba(2, 8, 23, 0.34), 0 1px 0 rgba(255, 255, 255, 0.035) inset",
  focus: "0 0 0 3px rgba(79, 140, 255, 0.22)",
};

const knLight = {
  bg: "#f7f8fa",
  layout: "#f7f8fa",
  shell: "#ffffff",
  surface: "#ffffff",
  surfaceRaised: "#ffffff",
  surfaceElevated: "#ffffff",
  surfaceSoft: "rgba(93, 102, 117, 0.08)",
  border: "#dde2ea",
  borderSubtle: "#edf0f4",
  text: "#151922",
  textSecondary: "#5d6675",
  textTertiary: "#8b94a3",
  textDisabled: "#a5adba",
  primary: "#235cff",
  primaryHover: "#174ce0",
  primaryActive: "#153fb8",
  primarySoft: "rgba(35, 92, 255, 0.1)",
  primarySofter: "rgba(35, 92, 255, 0.06)",
  accent: "#0ea5e9",
  accentHover: "#0284c7",
  accentActive: "#0369a1",
  accentSoft: "rgba(14, 165, 233, 0.1)",
  accentSofter: "rgba(14, 165, 233, 0.06)",
  info: "#0369a1",
  success: "#16875a",
  warning: "#b7791f",
  danger: "#d92d20",
  dangerActive: "#b42318",
  control: "#ffffff",
  controlHover: "#f3f6fa",
  controlActive: "#eef3ff",
  overlay: "#ffffff",
  overlayStrong: "#f8fafc",
  mask: "rgba(15, 23, 42, 0.34)",
  shadow: "0 16px 34px rgba(15, 23, 42, 0.13), 0 1px 0 rgba(255, 255, 255, 0.78) inset",
  focus: "0 0 0 3px rgba(35, 92, 255, 0.16)",
};

const darkTheme: ThemeConfig = {
  algorithm: antdTheme.darkAlgorithm,
  token: {
    colorPrimary: knDark.primary,
    colorPrimaryHover: knDark.primaryHover,
    colorPrimaryActive: knDark.primaryActive,
    colorInfo: knDark.info,
    colorSuccess: knDark.success,
    colorWarning: knDark.warning,
    colorError: knDark.danger,
    colorBgBase: knDark.bg,
    colorBgContainer: knDark.surface,
    colorBgLayout: knDark.layout,
    colorBgElevated: knDark.overlay,
    colorBgContainerDisabled: knDark.surfaceSoft,
    colorFillSecondary: knDark.primarySofter,
    colorFillTertiary: knDark.controlHover,
    colorFillQuaternary: knDark.surfaceSoft,
    colorBorderSecondary: knDark.borderSubtle,
    colorBorder: knDark.border,
    colorSplit: knDark.borderSubtle,
    colorText: knDark.text,
    colorTextSecondary: knDark.textSecondary,
    colorTextTertiary: knDark.textTertiary,
    colorTextDisabled: knDark.textDisabled,
    controlItemBgHover: knDark.controlHover,
    controlItemBgActive: knDark.primarySoft,
    controlOutline: "rgba(79, 140, 255, 0.18)",
    boxShadow: knDark.shadow,
    boxShadowSecondary: knDark.shadow,
    borderRadius: 8,
    borderRadiusLG: 8,
    borderRadiusSM: 6,
    controlHeight: 34,
    controlHeightLG: 38,
    controlHeightSM: 28,
    fontFamily,
    fontSize: 13,
  },
  components: {
    Layout: {
      siderBg: knDark.shell,
      headerBg: knDark.shell,
      bodyBg: knDark.layout,
    },
    Menu: {
      darkItemBg: knDark.shell,
      darkSubMenuItemBg: knDark.bg,
      darkItemSelectedBg: knDark.primarySoft,
      darkItemHoverBg: knDark.primarySofter,
      darkItemColor: knDark.textSecondary,
      darkItemSelectedColor: knDark.primaryHover,
    },
    Card: {
      colorBgContainer: knDark.surface,
      colorBorderSecondary: knDark.borderSubtle,
      headerBg: knDark.surface,
      headerFontSize: 14,
      headerFontSizeSM: 13,
      headerHeight: 44,
      headerHeightSM: 36,
      headerPadding: 16,
      headerPaddingSM: 12,
      bodyPadding: 16,
      bodyPaddingSM: 12,
      actionsBg: knDark.surfaceSoft,
      extraColor: knDark.textTertiary,
    },
    Table: {
      colorBgContainer: knDark.surface,
      colorBgElevated: knDark.overlay,
      headerBg: knDark.surfaceRaised,
      headerColor: knDark.textSecondary,
      headerSplitColor: knDark.borderSubtle,
      headerSortActiveBg: knDark.controlActive,
      headerSortHoverBg: knDark.controlHover,
      headerFilterHoverBg: knDark.controlHover,
      bodySortBg: knDark.surfaceSoft,
      rowHoverBg: knDark.controlHover,
      rowSelectedBg: knDark.primarySoft,
      rowSelectedHoverBg: "rgba(79, 140, 255, 0.2)",
      rowExpandedBg: knDark.surfaceSoft,
      borderColor: knDark.borderSubtle,
      footerBg: knDark.surfaceRaised,
      footerColor: knDark.textSecondary,
      filterDropdownBg: knDark.overlay,
      filterDropdownMenuBg: knDark.overlay,
      expandIconBg: knDark.control,
      stickyScrollBarBg: "rgba(154, 167, 181, 0.28)",
      stickyScrollBarBorderRadius: 6,
      headerBorderRadius: 8,
      selectionColumnWidth: 42,
      cellPaddingBlock: 10,
      cellPaddingInline: 12,
      cellPaddingBlockMD: 8,
      cellPaddingInlineMD: 10,
      cellPaddingBlockSM: 6,
      cellPaddingInlineSM: 8,
      cellFontSize: 13,
      cellFontSizeMD: 13,
      cellFontSizeSM: 12,
    },
    Input: {
      colorBgContainer: knDark.control,
      colorText: knDark.text,
      colorTextPlaceholder: knDark.textTertiary,
      colorBorder: knDark.border,
      addonBg: knDark.surfaceSoft,
      hoverBg: knDark.controlHover,
      activeBg: knDark.control,
      hoverBorderColor: knDark.primary,
      activeBorderColor: knDark.primary,
      activeShadow: knDark.focus,
      errorActiveShadow: "0 0 0 3px rgba(248, 113, 113, 0.16)",
      warningActiveShadow: "0 0 0 3px rgba(245, 158, 11, 0.16)",
      paddingInline: 10,
      paddingInlineSM: 8,
      paddingInlineLG: 12,
      paddingBlock: 5,
      paddingBlockSM: 3,
      paddingBlockLG: 7,
      inputFontSize: 13,
      inputFontSizeSM: 12,
      inputFontSizeLG: 14,
    },
    Button: {
      colorBgContainer: "transparent",
      defaultBg: knDark.control,
      defaultColor: knDark.textSecondary,
      defaultBorderColor: knDark.border,
      defaultHoverBg: knDark.controlHover,
      defaultHoverColor: knDark.text,
      defaultHoverBorderColor: knDark.primary,
      defaultActiveBg: knDark.controlActive,
      defaultActiveColor: knDark.primaryHover,
      defaultActiveBorderColor: knDark.primaryActive,
      defaultBgDisabled: knDark.surfaceSoft,
      dashedBgDisabled: knDark.surfaceSoft,
      primaryColor: "#ffffff",
      dangerColor: knDark.danger,
      borderColorDisabled: knDark.borderSubtle,
      defaultGhostColor: knDark.textSecondary,
      defaultGhostBorderColor: knDark.border,
      ghostBg: "transparent",
      textTextColor: knDark.textSecondary,
      textTextHoverColor: knDark.text,
      textTextActiveColor: knDark.primaryHover,
      textHoverBg: knDark.primarySofter,
      linkHoverBg: knDark.primarySofter,
      defaultShadow: "none",
      primaryShadow: "none",
      dangerShadow: "none",
      fontWeight: 500,
      iconGap: 6,
      paddingInline: 12,
      paddingInlineLG: 14,
      paddingInlineSM: 8,
      paddingBlock: 4,
      paddingBlockLG: 6,
      paddingBlockSM: 2,
      onlyIconSize: 16,
      onlyIconSizeLG: 18,
      onlyIconSizeSM: 14,
      contentFontSize: 13,
      contentFontSizeLG: 14,
      contentFontSizeSM: 12,
    },
    Modal: {
      colorBgElevated: knDark.overlay,
      contentBg: knDark.overlay,
      headerBg: knDark.overlay,
      footerBg: knDark.overlay,
      titleColor: knDark.text,
      titleFontSize: 15,
      titleLineHeight: 1.4,
      boxShadow: knDark.shadow,
      colorSplit: knDark.borderSubtle,
      colorText: knDark.text,
      colorTextSecondary: knDark.textSecondary,
      colorIcon: knDark.textTertiary,
      colorIconHover: knDark.text,
    },
    Drawer: {
      colorBgElevated: knDark.overlay,
      colorBgContainer: knDark.overlay,
      colorSplit: knDark.borderSubtle,
      colorText: knDark.text,
      colorTextSecondary: knDark.textSecondary,
      boxShadow: knDark.shadow,
      footerPaddingBlock: 12,
      footerPaddingInline: 16,
      draggerSize: 5,
      zIndexPopup: 1000,
    },
    Select: {
      colorBgContainer: knDark.control,
      colorBgElevated: knDark.overlay,
      colorBorder: knDark.border,
      colorText: knDark.text,
      colorTextPlaceholder: knDark.textTertiary,
      selectorBg: knDark.control,
      hoverBorderColor: knDark.primary,
      activeBorderColor: knDark.primary,
      activeOutlineColor: "rgba(79, 140, 255, 0.18)",
      optionSelectedColor: knDark.primaryHover,
      optionSelectedBg: knDark.primarySoft,
      optionSelectedFontWeight: 500,
      optionActiveBg: knDark.controlHover,
      optionPadding: "7px 10px",
      optionFontSize: 13,
      optionLineHeight: 1.45,
      optionHeight: 32,
      clearBg: knDark.control,
      multipleItemBg: knDark.surfaceSoft,
      multipleItemBorderColor: knDark.borderSubtle,
      multipleItemHeight: 24,
      multipleItemHeightSM: 20,
      multipleItemHeightLG: 28,
      multipleSelectorBgDisabled: knDark.surfaceSoft,
      multipleItemColorDisabled: knDark.textDisabled,
      multipleItemBorderColorDisabled: knDark.borderSubtle,
      singleItemHeightLG: 34,
      showArrowPaddingInlineEnd: 18,
      zIndexPopup: 1050,
    },
    Dropdown: {
      colorBgElevated: knDark.overlay,
      colorText: knDark.textSecondary,
      colorTextDescription: knDark.textTertiary,
      controlItemBgHover: knDark.controlHover,
      controlItemBgActive: knDark.primarySoft,
      colorSplit: knDark.borderSubtle,
      boxShadowSecondary: knDark.shadow,
      paddingBlock: 6,
      zIndexPopup: 1050,
    },
    Popover: {
      colorBgElevated: knDark.overlay,
      colorText: knDark.text,
      colorTextHeading: knDark.text,
      colorTextSecondary: knDark.textSecondary,
      colorBorderSecondary: knDark.borderSubtle,
      boxShadowSecondary: knDark.shadow,
      titleMinWidth: 160,
      zIndexPopup: 1030,
    },
    Tabs: {
      colorBorderSecondary: knDark.borderSubtle,
      cardBg: knDark.surfaceSoft,
      cardHeight: 34,
      cardHeightSM: 30,
      cardHeightLG: 38,
      cardPadding: "7px 12px",
      cardPaddingSM: "5px 10px",
      cardPaddingLG: "8px 14px",
      titleFontSize: 13,
      titleFontSizeSM: 12,
      titleFontSizeLG: 14,
      inkBarColor: knDark.primary,
      itemColor: knDark.textSecondary,
      itemHoverColor: knDark.text,
      itemActiveColor: knDark.primaryHover,
      itemSelectedColor: knDark.primaryHover,
      horizontalItemGutter: 18,
      horizontalItemMargin: "0 0 0 0",
      horizontalItemMarginRTL: "0 0 0 0",
      horizontalItemPadding: "9px 0",
      horizontalItemPaddingSM: "7px 0",
      horizontalItemPaddingLG: "10px 0",
      verticalItemPadding: "8px 16px",
      verticalItemMargin: "0 0 4px 0",
      cardGutter: 4,
      zIndexPopup: 1050,
    },
    Alert: {
      colorText: knDark.text,
      colorTextHeading: knDark.text,
      colorTextDescription: knDark.textSecondary,
      colorBorder: knDark.border,
      colorBorderSecondary: knDark.borderSubtle,
      defaultPadding: "10px 12px",
      withDescriptionPadding: "14px 16px",
      withDescriptionIconSize: 18,
    },
    Tag: {
      colorBorder: knDark.borderSubtle,
      defaultBg: knDark.surfaceSoft,
      defaultColor: knDark.textSecondary,
      solidTextColor: "#ffffff",
    },
  },
};

const lightTheme: ThemeConfig = {
  algorithm: antdTheme.defaultAlgorithm,
  token: {
    colorPrimary: knLight.primary,
    colorPrimaryHover: knLight.primaryHover,
    colorPrimaryActive: knLight.primaryActive,
    colorInfo: knLight.info,
    colorSuccess: knLight.success,
    colorWarning: knLight.warning,
    colorError: knLight.danger,
    colorBgBase: knLight.bg,
    colorBgContainer: knLight.surface,
    colorBgLayout: knLight.layout,
    colorBgElevated: knLight.overlay,
    colorBgContainerDisabled: knLight.surfaceSoft,
    colorFillSecondary: knLight.primarySofter,
    colorFillTertiary: knLight.controlHover,
    colorFillQuaternary: knLight.surfaceSoft,
    colorBorderSecondary: knLight.borderSubtle,
    colorBorder: knLight.border,
    colorSplit: knLight.borderSubtle,
    colorText: knLight.text,
    colorTextSecondary: knLight.textSecondary,
    colorTextTertiary: knLight.textTertiary,
    colorTextDisabled: knLight.textDisabled,
    controlItemBgHover: knLight.controlHover,
    controlItemBgActive: knLight.primarySoft,
    controlOutline: "rgba(35, 92, 255, 0.18)",
    boxShadow: knLight.shadow,
    boxShadowSecondary: knLight.shadow,
    borderRadius: 8,
    borderRadiusLG: 8,
    borderRadiusSM: 6,
    controlHeight: 34,
    controlHeightLG: 38,
    controlHeightSM: 28,
    fontFamily,
    fontSize: 13,
  },
  components: {
    Layout: {
      siderBg: knLight.shell,
      headerBg: knLight.shell,
      bodyBg: knLight.layout,
    },
    Menu: {
      itemSelectedBg: knLight.primarySoft,
      itemHoverBg: knLight.primarySofter,
      itemSelectedColor: knLight.primary,
      itemColor: knLight.textSecondary,
    },
    Card: {
      colorBgContainer: knLight.surface,
      colorBorderSecondary: knLight.borderSubtle,
      headerBg: knLight.surface,
      headerFontSize: 14,
      headerFontSizeSM: 13,
      headerHeight: 44,
      headerHeightSM: 36,
      headerPadding: 16,
      headerPaddingSM: 12,
      bodyPadding: 16,
      bodyPaddingSM: 12,
      actionsBg: knLight.surfaceRaised,
      extraColor: knLight.textTertiary,
    },
    Table: {
      colorBgContainer: knLight.surface,
      colorBgElevated: knLight.overlay,
      headerBg: knLight.surfaceRaised,
      headerColor: knLight.textSecondary,
      headerSplitColor: knLight.borderSubtle,
      headerSortActiveBg: knLight.controlActive,
      headerSortHoverBg: knLight.controlHover,
      headerFilterHoverBg: knLight.controlHover,
      bodySortBg: knLight.surfaceRaised,
      rowHoverBg: knLight.controlHover,
      rowSelectedBg: knLight.primarySoft,
      rowSelectedHoverBg: "rgba(35, 92, 255, 0.14)",
      rowExpandedBg: knLight.surfaceRaised,
      borderColor: knLight.borderSubtle,
      footerBg: knLight.surfaceRaised,
      footerColor: knLight.textSecondary,
      filterDropdownBg: knLight.overlay,
      filterDropdownMenuBg: knLight.overlay,
      expandIconBg: knLight.control,
      stickyScrollBarBg: "rgba(86, 98, 115, 0.25)",
      stickyScrollBarBorderRadius: 6,
      headerBorderRadius: 8,
      selectionColumnWidth: 42,
      cellPaddingBlock: 10,
      cellPaddingInline: 12,
      cellPaddingBlockMD: 8,
      cellPaddingInlineMD: 10,
      cellPaddingBlockSM: 6,
      cellPaddingInlineSM: 8,
      cellFontSize: 13,
      cellFontSizeMD: 13,
      cellFontSizeSM: 12,
    },
    Input: {
      colorBgContainer: knLight.control,
      colorText: knLight.text,
      colorTextPlaceholder: knLight.textTertiary,
      colorBorder: knLight.border,
      addonBg: knLight.surfaceSoft,
      hoverBg: knLight.controlHover,
      activeBg: knLight.control,
      hoverBorderColor: knLight.primary,
      activeBorderColor: knLight.primary,
      activeShadow: knLight.focus,
      errorActiveShadow: "0 0 0 3px rgba(220, 38, 38, 0.13)",
      warningActiveShadow: "0 0 0 3px rgba(183, 121, 31, 0.14)",
      paddingInline: 10,
      paddingInlineSM: 8,
      paddingInlineLG: 12,
      paddingBlock: 5,
      paddingBlockSM: 3,
      paddingBlockLG: 7,
      inputFontSize: 13,
      inputFontSizeSM: 12,
      inputFontSizeLG: 14,
    },
    Button: {
      colorBgContainer: "transparent",
      defaultBg: knLight.control,
      defaultColor: knLight.textSecondary,
      defaultBorderColor: knLight.border,
      defaultHoverBg: knLight.controlHover,
      defaultHoverColor: knLight.text,
      defaultHoverBorderColor: knLight.primary,
      defaultActiveBg: knLight.controlActive,
      defaultActiveColor: knLight.primaryActive,
      defaultActiveBorderColor: knLight.primaryActive,
      defaultBgDisabled: knLight.surfaceSoft,
      dashedBgDisabled: knLight.surfaceSoft,
      primaryColor: "#ffffff",
      dangerColor: knLight.danger,
      borderColorDisabled: knLight.borderSubtle,
      defaultGhostColor: knLight.textSecondary,
      defaultGhostBorderColor: knLight.border,
      ghostBg: "transparent",
      textTextColor: knLight.textSecondary,
      textTextHoverColor: knLight.text,
      textTextActiveColor: knLight.primaryActive,
      textHoverBg: knLight.primarySofter,
      linkHoverBg: knLight.primarySofter,
      defaultShadow: "none",
      primaryShadow: "none",
      dangerShadow: "none",
      fontWeight: 500,
      iconGap: 6,
      paddingInline: 12,
      paddingInlineLG: 14,
      paddingInlineSM: 8,
      paddingBlock: 4,
      paddingBlockLG: 6,
      paddingBlockSM: 2,
      onlyIconSize: 16,
      onlyIconSizeLG: 18,
      onlyIconSizeSM: 14,
      contentFontSize: 13,
      contentFontSizeLG: 14,
      contentFontSizeSM: 12,
    },
    Modal: {
      colorBgElevated: knLight.overlay,
      contentBg: knLight.overlay,
      headerBg: knLight.overlay,
      footerBg: knLight.overlay,
      titleColor: knLight.text,
      titleFontSize: 15,
      titleLineHeight: 1.4,
      boxShadow: knLight.shadow,
      colorSplit: knLight.borderSubtle,
      colorText: knLight.text,
      colorTextSecondary: knLight.textSecondary,
      colorIcon: knLight.textTertiary,
      colorIconHover: knLight.text,
    },
    Drawer: {
      colorBgElevated: knLight.overlay,
      colorBgContainer: knLight.overlay,
      colorSplit: knLight.borderSubtle,
      colorText: knLight.text,
      colorTextSecondary: knLight.textSecondary,
      boxShadow: knLight.shadow,
      footerPaddingBlock: 12,
      footerPaddingInline: 16,
      draggerSize: 5,
      zIndexPopup: 1000,
    },
    Select: {
      colorBgContainer: knLight.control,
      colorBgElevated: knLight.overlay,
      colorBorder: knLight.border,
      colorText: knLight.text,
      colorTextPlaceholder: knLight.textTertiary,
      selectorBg: knLight.control,
      hoverBorderColor: knLight.primary,
      activeBorderColor: knLight.primary,
      activeOutlineColor: "rgba(35, 92, 255, 0.14)",
      optionSelectedColor: knLight.primaryActive,
      optionSelectedBg: knLight.primarySoft,
      optionSelectedFontWeight: 500,
      optionActiveBg: knLight.controlHover,
      optionPadding: "7px 10px",
      optionFontSize: 13,
      optionLineHeight: 1.45,
      optionHeight: 32,
      clearBg: knLight.control,
      multipleItemBg: knLight.surfaceSoft,
      multipleItemBorderColor: knLight.borderSubtle,
      multipleItemHeight: 24,
      multipleItemHeightSM: 20,
      multipleItemHeightLG: 28,
      multipleSelectorBgDisabled: knLight.surfaceSoft,
      multipleItemColorDisabled: knLight.textDisabled,
      multipleItemBorderColorDisabled: knLight.borderSubtle,
      singleItemHeightLG: 34,
      showArrowPaddingInlineEnd: 18,
      zIndexPopup: 1050,
    },
    Dropdown: {
      colorBgElevated: knLight.overlay,
      colorText: knLight.textSecondary,
      colorTextDescription: knLight.textTertiary,
      controlItemBgHover: knLight.controlHover,
      controlItemBgActive: knLight.primarySoft,
      colorSplit: knLight.borderSubtle,
      boxShadowSecondary: knLight.shadow,
      paddingBlock: 6,
      zIndexPopup: 1050,
    },
    Popover: {
      colorBgElevated: knLight.overlay,
      colorText: knLight.text,
      colorTextHeading: knLight.text,
      colorTextSecondary: knLight.textSecondary,
      colorBorderSecondary: knLight.borderSubtle,
      boxShadowSecondary: knLight.shadow,
      titleMinWidth: 160,
      zIndexPopup: 1030,
    },
    Tabs: {
      colorBorderSecondary: knLight.borderSubtle,
      cardBg: knLight.surfaceSoft,
      cardHeight: 34,
      cardHeightSM: 30,
      cardHeightLG: 38,
      cardPadding: "7px 12px",
      cardPaddingSM: "5px 10px",
      cardPaddingLG: "8px 14px",
      titleFontSize: 13,
      titleFontSizeSM: 12,
      titleFontSizeLG: 14,
      inkBarColor: knLight.primary,
      itemColor: knLight.textSecondary,
      itemHoverColor: knLight.text,
      itemActiveColor: knLight.primaryActive,
      itemSelectedColor: knLight.primaryActive,
      horizontalItemGutter: 18,
      horizontalItemMargin: "0 0 0 0",
      horizontalItemMarginRTL: "0 0 0 0",
      horizontalItemPadding: "9px 0",
      horizontalItemPaddingSM: "7px 0",
      horizontalItemPaddingLG: "10px 0",
      verticalItemPadding: "8px 16px",
      verticalItemMargin: "0 0 4px 0",
      cardGutter: 4,
      zIndexPopup: 1050,
    },
    Alert: {
      colorText: knLight.text,
      colorTextHeading: knLight.text,
      colorTextDescription: knLight.textSecondary,
      colorBorder: knLight.border,
      colorBorderSecondary: knLight.borderSubtle,
      defaultPadding: "10px 12px",
      withDescriptionPadding: "14px 16px",
      withDescriptionIconSize: 18,
    },
    Tag: {
      colorBorder: knLight.borderSubtle,
      defaultBg: knLight.surfaceSoft,
      defaultColor: knLight.textSecondary,
      solidTextColor: "#ffffff",
    },
  },
};

export function ThemeProvider({ children }: { children: React.ReactNode }) {
  const [mode, setMode] = useState<ThemeMode>("light");
  const [isRestored, setIsRestored] = useState(false);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setMode(readBrowserThemeMode());
      setIsRestored(true);
    }, 0);
    return () => window.clearTimeout(timer);
  }, []);

  useEffect(() => {
    if (!isRestored) {
      return;
    }
    document.documentElement.setAttribute("data-theme", mode);
    window.localStorage.setItem("kubenova-theme-mode", mode);
  }, [isRestored, mode]);

  const value = useMemo(
    () => ({ mode, toggleTheme: () => setMode((m) => (m === "dark" ? "light" : "dark")) }),
    [mode],
  );

  const themeConfig = mode === "dark" ? darkTheme : lightTheme;

  return (
    <ThemeModeContext.Provider value={value}>
      <ConfigProvider locale={zhCN} theme={themeConfig}>
        {children}
      </ConfigProvider>
    </ThemeModeContext.Provider>
  );
}
