apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aiops

resources:
  - namespace.yaml
  - platform-config.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - redis.yaml
  - control-api.yaml
  - runtime-gateway.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: aiops-manager
  app.kubernetes.io/managed-by: kustomize
